FROM ros:melodic

RUN apt update && \
    apt install -y --no-install-recommends \
    python-pip \
    ros-melodic-rosbridge-server

# RUN source /opt/ros/melodic/setup.bash && \
#     roscore

# RUN source /opt/ros/melodic/setup.bash && \
#     roslaunch rosbridge_server rosbridge_websocket.launch    

ENTRYPOINT ["/opt/ros/melodic/setup.bash"]