version: "3"

services:
  ros-env:
    container_name: ros-env
    build:
      context: .
      dockerfile: Dockerfile.ros
    # image: ubuntu:20.04
    ports:
      - 8080:8080
      - 9090:9090
    tty: true
    stdin_open: true
    volumes:
      - ./:/website
      # future: thourgh docker file copy and start files
      
# enter container by command:
#   docker exec -it b-sh-env "/bin/bash"